export enum WashingMachineFunction {
  "ADD_WASH" = "ADD_WASH",
  "PANEL_AI_CONTROL" = "PANEL_AI_CONTROL",
  "INVERTER_DUTY_MOTOR" = "INVERTER_DUTY_MOTOR",
  "ELECTRONIC_DISPLAY" = "ELECTRONIC_DISPLAY"
 }